// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWzA_qstqTPmU7kvU4SoEuV1CJ3z6t5X8',
    appId: '1:315179533012:android:ea4846d85cf3887219f141',
    messagingSenderId: '315179533012',
    projectId: 'luzmed-79fc9',
    storageBucket: 'luzmed-79fc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQxgda5J0QRjd7xM7G9IJlEICrLWrL1S4',
    appId: '1:315179533012:ios:271ca5da9c0d637b19f141',
    messagingSenderId: '315179533012',
    projectId: 'luzmed-79fc9',
    storageBucket: 'luzmed-79fc9.firebasestorage.app',
    iosBundleId: 'com.example.luzmed',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBli6CdSQpaVkZnD7vunmV-afS1r2M1J_4',
    appId: '1:315179533012:web:c644fa4b164a7f0e19f141',
    messagingSenderId: '315179533012',
    projectId: 'luzmed-79fc9',
    authDomain: 'luzmed-79fc9.firebaseapp.com',
    storageBucket: 'luzmed-79fc9.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQxgda5J0QRjd7xM7G9IJlEICrLWrL1S4',
    appId: '1:315179533012:ios:271ca5da9c0d637b19f141',
    messagingSenderId: '315179533012',
    projectId: 'luzmed-79fc9',
    storageBucket: 'luzmed-79fc9.firebasestorage.app',
    iosBundleId: 'com.example.luzmed',
  );

}